redmine-3.3.2/config/routes.rb
# Redmine - project management software
# Copyright (C) 2006-2016  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new', :as => 'new_issues_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/rss_key', :to => 'my#reset_rss_key', :as => 'my_rss_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    shallow do
      resources :memberships, :controller => 'members', :only => [:index, :show, :new, :create, :update, :destroy] do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end
  
    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      collection do
        get 'report'
      end
    end
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

redmine-3.3.2/app/helpers/projects_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2016  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module ProjectsHelper
  def project_settings_tabs
    tabs = [{:name => 'info', :action => :edit_project, :partial => 'projects/edit', :label => :label_information_plural},
            {:name => 'modules', :action => :select_project_modules, :partial => 'projects/settings/modules', :label => :label_module_plural},
            {:name => 'members', :action => :manage_members, :partial => 'projects/settings/members', :label => :label_member_plural},
            {:name => 'versions', :action => :manage_versions, :partial => 'projects/settings/versions', :label => :label_version_plural},
            {:name => 'categories', :action => :manage_categories, :partial => 'projects/settings/issue_categories', :label => :label_issue_category_plural},
            {:name => 'wiki', :action => :manage_wiki, :partial => 'projects/settings/wiki', :label => :label_wiki},
            {:name => 'repositories', :action => :manage_repository, :partial => 'projects/settings/repositories', :label => :label_repository_plural},
            {:name => 'boards', :action => :manage_boards, :partial => 'projects/settings/boards', :label => :label_board_plural},
            {:name => 'activities', :action => :manage_project_activities, :partial => 'projects/settings/activities', :label => :enumeration_activities}
            ]
    tabs.select {|tab| User.current.allowed_to?(tab[:action], @project)}
  end

  def parent_project_select_tag(project)
    selected = project.parent
    # retrieve the requested parent project
    parent_id = (params[:project] && params[:project][:parent_id]) || params[:parent_id]
    if parent_id
      selected = (parent_id.blank? ? nil : Project.find(parent_id))
    end

    options = ''
    options << "<option value=''>&nbsp;</option>" if project.allowed_parents.include?(nil)
    options << project_tree_options_for_select(project.allowed_parents.compact, :selected => selected)
    content_tag('select', options.html_safe, :name => 'project[parent_id]', :id => 'project_parent_id')
  end

  def render_project_action_links
    links = []
    if User.current.allowed_to?(:add_project, nil, :global => true)
      links << link_to(l(:label_project_new), new_project_path, :class => 'icon icon-add')
    end
    if User.current.allowed_to?(:view_issues, nil, :global => true)
      links << link_to(l(:label_issue_view_all), issues_path)
    end
    if User.current.allowed_to?(:view_time_entries, nil, :global => true)
      links << link_to(l(:label_overall_spent_time), time_entries_path)
    end
    links << link_to(l(:label_overall_activity), activity_path)
    links.join(" | ").html_safe
  end

  # Renders the projects index
  def render_project_hierarchy(projects)
    render_project_nested_lists(projects) do |project|
      s = link_to_project(project, {}, :class => "#{project.css_classes} #{User.current.member_of?(project) ? 'my-project' : nil}")
      if project.description.present?
        s << content_tag('div', textilizable(project.short_description, :project => project), :class => 'wiki description')
      end
      s
    end
  end

  # Returns a set of options for a select field, grouped by project.
  def version_options_for_select(versions, selected=nil)
    grouped = Hash.new {|h,k| h[k] = []}
    versions.each do |version|
      grouped[version.project.name] << [version.name, version.id]
    end

    selected = selected.is_a?(Version) ? selected.id : selected
    if grouped.keys.size > 1
      grouped_options_for_select(grouped, selected)
    else
      options_for_select((grouped.values.first || []), selected)
    end
  end

  def project_default_version_options(project)
    versions = project.shared_versions.open.to_a
    if project.default_version && !versions.include?(project.default_version)
      versions << project.default_version
    end
    version_options_for_select(versions, project.default_version)
  end

  def format_version_sharing(sharing)
    sharing = 'none' unless Version::VERSION_SHARINGS.include?(sharing)
    l("label_version_sharing_#{sharing}")
  end

  def render_boards_tree(boards, parent=nil, level=0, &block)
    selection = boards.select {|b| b.parent == parent}
    return '' if selection.empty?

    s = ''.html_safe
    selection.each do |board|
      node = capture(board, level, &block)
      node << render_boards_tree(boards, board, level+1, &block)
      s << content_tag('div', node)
    end
    content_tag('div', s, :class => 'sort-level')
  end

  def render_api_includes(project, api)
    api.array :trackers do
      project.trackers.each do |tracker|
        api.tracker(:id => tracker.id, :name => tracker.name)
      end
    end if include_in_api_response?('trackers')

    api.array :issue_categories do
      project.issue_categories.each do |category|
        api.issue_category(:id => category.id, :name => category.name)
      end
    end if include_in_api_response?('issue_categories')

    api.array :enabled_modules do
      project.enabled_modules.each do |enabled_module|
        api.enabled_module(:id => enabled_module.id, :name => enabled_module.name)
      end
    end if include_in_api_response?('enabled_modules')

  end
end

redmine-3.3.2/app/views/projects/settings/_activities.html.erb
<%= form_tag(project_enumerations_path(@project), :method => :put, :class => "tabular") do %>

<table class="list">
  <thead><tr>
    <th><%= l(:field_name) %></th>
    <th><%= l(:enumeration_system_activity) %></th>
    <% TimeEntryActivity.new.available_custom_fields.each do |value| %>
    <th><%= value.name %></th>
    <% end %>
    <th><%= l(:field_active) %></th>
  </tr></thead>

  <% @project.activities(true).each do |enumeration| %>
  <%= fields_for "enumerations[#{enumeration.id}]", enumeration do |ff| %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td class="name">
      <%= ff.hidden_field :parent_id, :value => enumeration.id unless enumeration.project %>
      <%= enumeration %>
    </td>
    <td class="tick"><%= checked_image !enumeration.project %></td>
    <% enumeration.custom_field_values.each do |value| %>
    <td>
      <%= custom_field_tag "enumerations[#{enumeration.id}]", value %>
    </td>
    <% end %>
    <td>
      <%= ff.check_box :active %>
    </td>
  </tr>
  <% end %>
  <% end %>
</table>

<div class="contextual">
<%= link_to(l(:button_reset), project_enumerations_path(@project),
            :method => :delete,
            :data => {:confirm => l(:text_are_you_sure)},
            :class => 'icon icon-del') %>
</div>

<%= submit_tag l(:button_save) %>
<% end %>

redmine-3.3.2/app/views/projects/settings/_boards.html.erb
<% if @project.boards.any? %>
<div class="table-list boards">
  <div class="table-list-header">
    <div class="table-list-cell"><%= l(:label_board) %></div>
  </div>
  <%= render_boards_tree(@project.boards) do |board, level| %>
  <div class="table-list-row <%= cycle 'odd', 'even' %>">
    <div class="table-list-cell name" style="padding-left: <%= 2 + level * 16 %>px">
      <%= link_to board.name, project_board_path(@project, board) %>
    </div>
    <div class="table-list-cell description"><%= board.description %></div>
    <div class="table-list-cell buttons">
    <% if User.current.allowed_to?(:manage_boards, @project) %>
      <%= reorder_handle(board) %>
      <%= link_to l(:button_edit), edit_project_board_path(@project, board), :class => 'icon icon-edit' %>
      <%= delete_link project_board_path(@project, board) %>
    <% end %>
    </div>
  </div>
  <% end %>
</div>

<%= javascript_tag do %>
  $(function() { $("div.sort-level").positionedItems(); });
<% end %>

<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% if User.current.allowed_to?(:manage_boards, @project) %>
<p><%= link_to l(:label_board_new), new_project_board_path(@project), :class => 'icon icon-add' %></p>
<% end %>

redmine-3.3.2/app/views/projects/settings/_issue_categories.html.erb
<% if @project.issue_categories.any? %>
<table class="list">
  <thead><tr>
    <th><%= l(:label_issue_category) %></th>
    <th><%= l(:field_assigned_to) %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for category in @project.issue_categories %>
  <% unless category.new_record? %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td class="name"><%= category.name  %></td>
    <td><%= category.assigned_to.name if category.assigned_to %></td>
    <td class="buttons">
      <% if User.current.allowed_to?(:manage_categories, @project) %>
        <%= link_to l(:button_edit), edit_issue_category_path(category), :class => 'icon icon-edit' %>
        <%= delete_link issue_category_path(category) %>
      <% end %>
    </td>
  </tr>
  <% end %>
<% end %>
    </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to l(:label_issue_category_new), new_project_issue_category_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_categories, @project) %></p>

redmine-3.3.2/app/views/projects/settings/_members.html.erb
<% roles = Role.find_all_givable
   members = @project.memberships.includes(:member_roles, :roles, :principal).to_a.sort %>

<p><%= link_to l(:label_member_new), new_project_membership_path(@project), :remote => true, :class => "icon icon-add" %></p>

<% if members.any? %>
<table class="list members">
  <thead>
    <tr>
      <th><%= l(:label_user) %> / <%= l(:label_group) %></th>
      <th><%= l(:label_role_plural) %></th>
      <th style="width:15%"></th>
      <%= call_hook(:view_projects_settings_members_table_header, :project => @project) %>
    </tr>
  </thead>
  <tbody>
  <% members.each do |member| %>
  <% next if member.new_record? %>
  <tr id="member-<%= member.id %>" class="<%= cycle 'odd', 'even' %> member">
  <td class="name <%= member.principal.class.name.downcase %>"><%= link_to_user member.principal %></td>
  <td class="roles">
    <span id="member-<%= member.id %>-roles"><%= member.roles.sort.collect(&:to_s).join(', ') %></span>
      <%= form_for(member,
                   {:as => :membership, :remote => true,
                    :url => membership_path(member),
                    :method => :put,
                    :html => { :id => "member-#{member.id}-roles-form", :class => 'hol' }}
             ) do |f| %>
        <p>
          <% roles.each do |role| %>
          <label>
            <%= check_box_tag('membership[role_ids][]',
                              role.id, member.roles.include?(role),
                              :id => nil,
                              :disabled => !member.role_editable?(role)) %> <%= role %>
          </label><br />
          <% end %>
        </p>
        <%= hidden_field_tag 'membership[role_ids][]', '', :id => nil %>
        <p>
          <%= submit_tag l(:button_save), :class => "small" %>
          <%= link_to_function(l(:button_cancel),
                               "$('#member-#{member.id}-roles').show(); $('#member-#{member.id}-roles-form').hide(); return false;") %>
        </p>
      <% end %>
  </td>
  <td class="buttons">
      <%= link_to_function l(:button_edit),
                           "$('#member-#{member.id}-roles').hide(); $('#member-#{member.id}-roles-form').show(); return false;",
                           :class => 'icon icon-edit' %>
      <%= delete_link membership_path(member),
                      :remote => true,
                      :data => (!User.current.admin? && member.include?(User.current) ? {:confirm => l(:text_own_membership_delete_confirmation)} : {}) if member.deletable? %>
  </td>
  <%= call_hook(:view_projects_settings_members_table_row, { :project => @project, :member => member}) %>
  </tr>
<% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

redmine-3.3.2/app/views/projects/settings/_modules.html.erb
<%= form_for @project,
            :url => { :action => 'modules', :id => @project },
            :html => {:id => 'modules-form',
                      :method => :post} do |f| %>

<fieldset class="box">
<legend><%= l(:text_select_project_modules) %></legend>

<% Redmine::AccessControl.available_project_modules.each do |m| %>
<p><label><%= check_box_tag 'enabled_module_names[]', m, @project.module_enabled?(m), :id => nil -%>
 <%= l_or_humanize(m, :prefix => "project_module_") %></label></p>
<% end %>
</fieldset>
<p><%= check_all_links 'modules-form' %></p>

<p><%= submit_tag l(:button_save) %></p>

<% end %>

redmine-3.3.2/app/views/projects/settings/_repositories.html.erb
<% if @project.repositories.any? %>
<table class="list">
  <thead>
    <tr>
      <th><%= l(:field_identifier) %></th>
      <th><%= l(:field_repository_is_default) %></th>
      <th><%= l(:label_scm) %></th>
      <th><%= l(:label_repository) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @project.repositories.sort.each do |repository| %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td class="name">
      <%= link_to repository.identifier, 
            {:controller => 'repositories', :action => 'show',:id => @project, :repository_id => repository.identifier_param} if repository.identifier.present? %>
      </td>
      <td><%= checked_image repository.is_default? %></td>
      <td><%= repository.scm_name %></td>
      <td><%= repository.url %></td>
      <td class="buttons">
      <% if User.current.allowed_to?(:manage_repository, @project) %>
        <%= link_to(l(:label_user_plural), committers_repository_path(repository),
             :class => 'icon icon-user') %>
        <%= link_to(l(:button_edit), edit_repository_path(repository),
             :class => 'icon icon-edit') %>
        <%= delete_link repository_path(repository) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% if User.current.allowed_to?(:manage_repository, @project) %>
  <p><%= link_to l(:label_repository_new), new_project_repository_path(@project), :class => 'icon icon-add' %></p>
<% end %>

redmine-3.3.2/app/views/projects/settings/_versions.html.erb
<% if @project.shared_versions.any? %>
<table class="list versions">
  <thead><tr>
    <th><%= l(:label_version) %></th>
    <th><%= l(:field_effective_date) %></th>
    <th><%= l(:field_description) %></th>
    <th><%= l(:field_status) %></th>
    <th><%= l(:field_sharing) %></th>
    <th><%= l(:label_wiki_page) %></th>
    <th style="width:15%"></th>
    </tr></thead>
  <tbody>
<% for version in @project.shared_versions.sort %>
    <tr class="version <%= cycle 'odd', 'even' %> <%=h version.status %> <%= 'shared' if version.project != @project %>">
    <td class="name"><%= link_to_version version %></td>
    <td class="date"><%= format_date(version.effective_date) %></td>
    <td class="description"><%= version.description %></td>
    <td class="status"><%= l("version_status_#{version.status}") %></td>
    <td class="sharing"><%=h format_version_sharing(version.sharing) %></td>
    <td><%= link_to_if_authorized(version.wiki_page_title, {:controller => 'wiki', :action => 'show', :project_id => version.project, :id => Wiki.titleize(version.wiki_page_title)}) || h(version.wiki_page_title) unless version.wiki_page_title.blank? || version.project.wiki.nil? %></td>
    <td class="buttons">
      <% if version.project == @project && User.current.allowed_to?(:manage_versions, @project) %>
        <%= link_to l(:button_edit), edit_version_path(version), :class => 'icon icon-edit' %>
        <%= delete_link version_path(version) %>
      <% end %>
     </td>
    </tr>
<% end; reset_cycle %>
    </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<div class="contextual">
<% if @project.versions.any? %>
  <%= link_to l(:label_close_versions), close_completed_project_versions_path(@project), :method => :put %>
<% end %>
</div>

<p><%= link_to l(:label_version_new), new_project_version_path(@project, :back_url => ''), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, @project) %></p>

redmine-3.3.2/app/views/projects/settings/_wiki.html.erb
<%= labelled_form_for @wiki,
                   :as => :wiki,
                   :url => { :controller => 'wikis', :action => 'edit', :id => @project },
                   :remote => true, :method => 'post' do |f| %>

<%= error_messages_for 'wiki' %>

<div class="box tabular">
<p><%= f.text_field :start_page, :size => 60, :required => true %>
<em class="info"><%= l(:text_unallowed_characters) %>: , . / ? ; : |</em></p>
</div>

<div class="contextual">
<%= link_to(l(:button_delete), {:controller => 'wikis', :action => 'destroy', :id => @project},
            :class => 'icon icon-del') if @wiki && !@wiki.new_record? %>
</div>

<%= submit_tag((@wiki.nil? || @wiki.new_record?) ? l(:button_create) : l(:button_save)) %>
<% end %>