redmine-6.0.5/config/routes.rb
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
      get 'tab/:name', :action => 'issue_tab', :as => 'tab'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      match 'bulk_update', :via => [:post, :patch]
    end
    resources :time_entries, :controller => 'timelog', :only => [:new, :create]
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]
  get '/queries/filter', :to => 'queries#filter', :as => 'queries_filter'

  resources :news, :only => [:index, :show, :edit, :update, :destroy, :create, :new]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    member do
      # Used when updating the edit form of an existing time entry
      patch 'edit', :to => 'timelog#edit'
    end
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete
  # Used to update the new time entry form
  post '/time_entries/new', :to => 'timelog#new'
  # Used to update the bulk edit time entry form
  post '/time_entries/bulk_edit', :to => 'timelog#bulk_edit'

  get 'projects/:id/activity', :to => 'activities#index', :as => :project_activity
  get 'activity', :to => 'activities#index'

  # repositories routes
  get 'projects/:id/repository/:repository_id/statistics', :to => 'repositories#stats'
  get 'projects/:id/repository/:repository_id/graph', :to => 'repositories#graph'
  post 'projects/:id/repository/:repository_id/fetch_changesets', :to => 'repositories#fetch_changesets'

  get 'projects/:id/repository/:repository_id/revisions/:rev', :to => 'repositories#revision'
  get 'projects/:id/repository/:repository_id/revision', :to => 'repositories#revision'
  post   'projects/:id/repository/:repository_id/revisions/:rev/issues', :to => 'repositories#add_related_issue'
  delete 'projects/:id/repository/:repository_id/revisions/:rev/issues/:issue_id', :to => 'repositories#remove_related_issue'
  get 'projects/:id/repository/:repository_id/revisions', :to => 'repositories#revisions'
  %w(browse show entry raw annotate).each do |action|
    get "projects/:id/repository/:repository_id/revisions/:rev/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/}
  end

  %w(browse entry raw changes annotate).each do |action|
    get "projects/:id/repository/:repository_id/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:path => /.*/}
  end

  get "projects/:id/repository/:repository_id/revisions/:rev/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/, :format => /(html|diff)/ }

  get "projects/:id/repository/:repository_id/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:path => /.*/, :format => /(html|diff)/ }

  get 'projects/:id/repository/:repository_id/show/*path', :to => 'repositories#show', :format => 'html', :constraints => {:path => /.*/}

  get 'projects/:id/repository/:repository_id', :to => 'repositories#show', :path => nil
  get 'projects/:id/repository', :to => 'repositories#show', :path => nil

  # additional routes for having the file name at the end of url
  get 'attachments/:id/:filename', :to => 'attachments#show', :id => /\d+/, :filename => /.*/, :as => 'named_attachment', :format => 'html'
  get 'attachments/download/:id/:filename', :to => 'attachments#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_attachment', :format => 'html'
  get 'attachments/download/:id', :to => 'attachments#download', :id => /\d+/
  get 'attachments/thumbnail/:id(/:size)', :to => 'attachments#thumbnail', :id => /\d+/, :size => /\d+/, :as => 'thumbnail'
  resources :attachments, :only => [:show, :update, :destroy]

  # register plugin object types with ObjectTypeConstraint.register_object_type(PluginModel.name.underscore.pluralize')
  constraints Redmine::Acts::Attachable::ObjectTypeConstraint do
    get 'attachments/:object_type/:object_id/edit', :to => 'attachments#edit_all', :as => :object_attachments_edit
    patch 'attachments/:object_type/:object_id', :to => 'attachments#update_all', :as => :object_attachments
    get 'attachments/:object_type/:object_id/download', :to => 'attachments#download_all', :as => :object_attachments_download
  end

  resources :groups do
    resources :memberships, :controller => 'principal_memberships'
    member do
      get 'autocomplete_for_user'
    end
  end

  get 'groups/:id/users/new', :to => 'groups#new_users', :id => /\d+/, :as => 'new_group_users'
  post 'groups/:id/users', :to => 'groups#add_users', :id => /\d+/, :as => 'group_users'
  delete 'groups/:id/users/:user_id', :to => 'groups#remove_user', :id => /\d+/, :as => 'group_user'

  resources :trackers, :except => :show do
    collection do
      match 'fields', :via => [:get, :post]
    end
  end
  resources :issue_statuses, :except => :show do
    collection do
      post 'update_issue_done_ratio'
    end
  end
  resources :custom_fields, :except => :show do
    resources :enumerations, :controller => 'custom_field_enumerations', :except => [:show, :new, :edit]
    put 'enumerations', :to => 'custom_field_enumerations#update_each'
  end
  resources :roles do
    collection do
      get 'permissions'
      post 'permissions', :to => 'roles#update_permissions'
    end
  end
  resources :enumerations, :except => :show
  match 'enumerations/:type', :to => 'enumerations#index', :via => :get

  get '(projects/:id)/search', :controller => 'search', :action => 'index', :as => 'search'


  get  'mail_handler', :to => 'mail_handler#new'
  post 'mail_handler', :to => 'mail_handler#index'

  get 'admin', :to => 'admin#index'
  get 'admin/projects', :to => 'admin#projects'
  get 'admin/plugins', :to => 'admin#plugins'
  get 'admin/info', :to => 'admin#info'
  post 'admin/test_email', :to => 'admin#test_email', :as => 'test_email'
  post 'admin/default_configuration', :to => 'admin#default_configuration'

  match '/admin/projects_context_menu', :to => 'context_menus#projects', :as => 'projects_context_menu', :via => [:get, :post]

  resources :auth_sources do
    member do
      get 'test_connection', :as => 'try_connection'
    end
    collection do
      get 'autocomplete_for_new_user'
    end
  end

  resources :workflows, only: [:index] do
    collection do
      get 'edit'
      patch 'update'
      get 'permissions'
      patch 'update_permissions'
      get 'copy'
      post 'duplicate'
    end
  end

  match 'settings', :controller => 'settings', :action => 'index', :via => :get
  match 'settings/edit', :controller => 'settings', :action => 'edit', :via => [:get, :post]
  match 'settings/plugin/:id', :controller => 'settings', :action => 'plugin', :via => [:get, :post], :as => 'plugin_settings'

  match 'sys/projects', :to => 'sys#projects', :via => :get
  match 'sys/projects/:id/repository', :to => 'sys#create_project_repository', :via => :post
  match 'sys/fetch_changesets', :to => 'sys#fetch_changesets', :via => [:get, :post]

  match 'uploads', :to => 'attachments#upload', :via => :post

  get 'robots.:format', :to => 'welcome#robots', :constraints => {:format => 'txt'}

  get 'help/wiki_syntax/(:type)', :controller => 'help', :action => 'show_wiki_syntax', :constraints => { :type => /detailed/ }, :as => 'help_wiki_syntax'
  get 'help/code_highlighting', :controller => 'help', :action => 'show_code_highlighting',  :as => 'help_code_highlighting'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  Redmine::Plugin.directory.glob("*/config/routes.rb").sort.each do |plugin_routes_path|
    instance_eval(plugin_routes_path.read, plugin_routes_path.to_s)
  rescue SyntaxError, StandardError => e
    plugin_name = plugin_routes_path.parent.parent.basename.to_s
    puts "An error occurred while loading the routes definition of #{plugin_name} plugin (#{plugin_routes_path}): #{e.message}."

redmine-6.0.5/app/controllers/roles_controller.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class RolesController < ApplicationController
  layout 'admin'
  self.main_menu = false

  before_action :require_admin, :except => [:index, :show]
  before_action :require_admin_or_api_request, :only => [:index, :show]
  before_action :find_role, :only => [:show, :edit, :update, :destroy]
  accept_api_auth :index, :show

  include RolesHelper

  require_sudo_mode :create, :update, :destroy

  def index
    respond_to do |format|
      format.html do
        @roles = Role.sorted.to_a
        render :layout => false if request.xhr?
      end
      format.api do
        @roles = Role.givable.to_a
      end
    end
  end

  def show
    respond_to do |format|
      format.api
    end
  end

  def new
    # Prefills the form with 'Non member' role permissions by default
    @role = Role.new
    @role.safe_attributes = params[:role] || {:permissions => Role.non_member.permissions}
    if params[:copy].present? && @copy_from = Role.find_by_id(params[:copy])
      @role.copy_from(@copy_from)
    end
    @roles = Role.sorted.to_a
  end

  def create
    @role = Role.new
    @role.safe_attributes = params[:role]
    if request.post? && @role.save
      # workflow copy
      if params[:copy_workflow_from].present? && (copy_from = Role.find_by_id(params[:copy_workflow_from]))
        @role.copy_workflow_rules(copy_from)
      end
      flash[:notice] = l(:notice_successful_create)
      redirect_to roles_path
    else
      @roles = Role.sorted.to_a
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    @role.safe_attributes = params[:role]
    if @role.save
      respond_to do |format|
        format.html do
          flash[:notice] = l(:notice_successful_update)
          redirect_to roles_path(:page => params[:page])
        end
        format.js {head :ok}
      end
    else
      respond_to do |format|
        format.html {render :action => 'edit'}
        format.js   {head :unprocessable_content}
      end
    end
  end

  def destroy
    begin
      @role.destroy
    rescue
      flash[:error] =  l(:error_can_not_remove_role)
    end
    redirect_to roles_path
  end

  def permissions
    scope = Role.sorted
    if params[:ids].present?
      scope = scope.where(:id => params[:ids])
    end
    @roles = scope.to_a
    @permissions = Redmine::AccessControl.permissions.reject(&:public?)
    respond_to do |format|
      format.html
      format.csv do
        send_data(permissions_to_csv(@roles, @permissions), :type => 'text/csv; header=present', :filename => 'permissions.csv')
      end
    end
  end

  def update_permissions
    @roles = Role.where(:id => params[:permissions].keys)
    @roles.each do |role|
      role.permissions = params[:permissions][role.id.to_s]
      role.save
    end
    flash[:notice] = l(:notice_successful_update)
    redirect_to roles_path
  end

  private

  def find_role
    @role = Role.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

redmine-6.0.5/app/helpers/roles_helper.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module RolesHelper
  include ApplicationHelper

  def permissions_to_csv(roles, permissions)
    Redmine::Export::CSV.generate(:encoding => params[:encoding]) do |csv|
      # csv header fields
      headers = [l(:field_cvs_module), l(:label_permissions)] + roles.collect(&:name)
      csv << headers
      # csv lines
      perms_by_module = permissions.group_by {|p| p.project_module.to_s}
      perms_by_module.keys.sort.each do |mod|
        perms_by_module[mod].each do |p|
          names = [
            l_or_humanize(p.project_module.to_s, :prefix => 'project_module_'),
            l_or_humanize(p.name, :prefix => 'permission_').to_s,
          ]
          fields = names + roles.collect do |role|
            if role.setable_permissions.include?(p)
              format_object(role.permissions.include?(p.name), html: false)
            else
              ''
            end
          end
          csv << fields
        end
      end
    end
  end
end

redmine-6.0.5/app/views/roles/_form.html.erb
<%= error_messages_for 'role' %>

<div class="box tabular">
  <% unless @role.builtin? %>
    <p><%= f.text_field :name, :required => true %></p>
    <p><%= f.check_box :assignable %></p>
  <% end %>

  <% unless @role.anonymous? %>
    <p class="view_issues_shown"><%= f.select :issues_visibility, Role::ISSUES_VISIBILITY_OPTIONS.collect {|v| [l(v.last), v.first]} %></p>
  <% end %>

  <% unless @role.anonymous? %>
    <p class="view_time_entries_shown"><%= f.select :time_entries_visibility, Role::TIME_ENTRIES_VISIBILITY_OPTIONS.collect {|v| [l(v.last), v.first]} %></p>
  <% end %>

  <p><%= f.select :users_visibility, Role::USERS_VISIBILITY_OPTIONS.collect {|v| [l(v.last), v.first]} %></p>

  <% unless @role.builtin? %>
    <p class="manage_members_shown">
      <label><%= l(:label_member_management) %></label>
      <label class="block">
        <%= radio_button_tag 'role[all_roles_managed]', 1, @role.all_roles_managed?, :id => 'role_all_roles_managed_on',
              :data => {:disables => '.role_managed_role input'} %>
        <%= l(:label_member_management_all_roles) %>
      </label>
      <label class="block">
        <%= radio_button_tag 'role[all_roles_managed]', 0, !@role.all_roles_managed?, :id => 'role_all_roles_managed_off',
              :data => {:enables => '.role_managed_role input'} %>
        <%= l(:label_member_management_selected_roles_only) %>:
      </label>
      <% Role.givable.sorted.each do |role| %>
        <label class="block role_managed_role" style="padding-left:2em;">
          <%= check_box_tag 'role[managed_role_ids][]', role.id, @role.managed_roles.to_a.include?(role), :id => nil %>
          <%= role.name %>
        </label>
      <% end %>
      <%= hidden_field_tag 'role[managed_role_ids][]', '' %>
    </p>
  <% end %>

  <% unless @role.anonymous? %>
    <p><%= f.select :default_time_entry_activity_id, options_from_collection_for_select(TimeEntryActivity.active.shared, :id, :name, @role.default_time_entry_activity_id), :include_blank => l(:label_none) %></p>
  <% end %>

  <% if @role.new_record? && @roles.any? %>
    <p><label for="copy_workflow_from"><%= l(:label_copy_workflow_from) %></label>
    <%= select_tag(:copy_workflow_from, content_tag("option") + options_from_collection_for_select(@roles, :id, :name, params[:copy_workflow_from] || @copy_from.try(:id))) %></p>
  <% end %>
</div>

<h3><%= l(:label_permissions) %></h3>
<div class="box tabular" id="permissions">
<% setable_permissions = @role.setable_permissions %>
<% perms_by_module = setable_permissions.group_by {|p| p.project_module.to_s} %>
<% perms_by_module.keys.sort.each do |mod| %>
    <% module_name = mod.blank? ? 'module_project' : "module_#{mod}" %>
    <fieldset id="<%= module_name %>"><legend><%= toggle_checkboxes_link("##{module_name}\ input") %><%= mod.blank? ? l(:label_project) : l_or_humanize(mod, :prefix => 'project_module_') %></legend>
    <% perms_by_module[mod].each do |permission| %>
        <label class="floating">
        <%= check_box_tag 'role[permissions][]', permission.name, (@role.permissions.include? permission.name),
              :id => "role_permissions_#{permission.name}",
              :data => {:shows => ".#{permission.name}_shown"} %>
        <%= l_or_humanize(permission.name, :prefix => 'permission_') %>
        </label>
    <% end %>
    </fieldset>
<% end %>
<br /><%= check_all_links 'permissions' %>
<%= hidden_field_tag 'role[permissions][]', '' %>
</div>

<div id="role-permissions-trackers" class="view_issues_shown">
<h3><%= l(:label_issue_tracking) %></h3>
<% permissions = [:view_issues, :add_issues, :edit_issues, :add_issue_notes, :delete_issues] & setable_permissions.collect(&:name) %>

<div class="autoscroll">
<table class="list">
  <thead>
    <tr>
      <th><%= l(:label_tracker) %></th>
      <% permissions.each do |permission| %>
      <th class="<%= "#{permission}_shown" %>"><%= l("permission_#{permission}") %></th>
      <% end %>
  </thead>
  <tbody>
    <tr class='permissions-all-trackers'>
      <td class="name"><%= toggle_checkboxes_link('tr.permissions-all-trackers input[type="checkbox"]') %><b><%= l(:label_tracker_all) %></b></td>
      <% permissions.each do |permission| %>
      <td class="<%= "#{permission}_shown" %>">
        <%= hidden_field_tag "role[permissions_all_trackers][#{permission}]", '0', :id => nil %>
        <%= check_box_tag "role[permissions_all_trackers][#{permission}]",
              '1',
              @role.permissions_all_trackers?(permission),
              :class => "#{permission}_shown",
              :data => {:disables => ".#{permission}_tracker"} %>
      </td>
      <% end %>
    </tr>
    <% Tracker.sorted.all.each do |tracker| %>
    <tr class="permissions-tracker-<%= tracker.id %>">
      <td class="name"><%= toggle_checkboxes_link("tr.permissions-tracker-#{tracker.id} input:enabled") %><%= tracker.name %></td>
      <% permissions.each do |permission| %>
      <td class="<%= "#{permission}_shown" %>"><%= check_box_tag "role[permissions_tracker_ids][#{permission}][]",
                tracker.id,
                @role.permissions_tracker_ids?(permission, tracker.id),
                :class => "#{permission}_tracker",
                :id => "role_permissions_tracker_ids_add_issues_#{tracker.id}" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<% permissions.each do |permission| %>
  <%= hidden_field_tag "role[permissions_tracker_ids][#{permission}][]", '' %>
<% end %>
</div>

redmine-6.0.5/app/views/roles/edit.html.erb
<%= title [l(:label_role_plural), roles_path], @role.name %>

<%= labelled_form_for @role do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

redmine-6.0.5/app/views/roles/index.html.erb
<div class="contextual">
<%= link_to sprite_icon('add', l(:label_role_new)), new_role_path, :class => 'icon icon-add' %>
<%= link_to sprite_icon('summary', l(:label_permissions_report)), permissions_roles_path, :class => 'icon icon-summary' %>
</div>

<h2><%=l(:label_role_plural)%></h2>

<table class="list roles">
  <thead><tr>
    <th><%=l(:label_role)%></th>
  <th></th>
  <th></th>
  </tr></thead>
  <tbody>
<% for role in @roles %>
  <tr class="<%= role.builtin? ? "builtin" : "givable" %>">
  <td class="name"><%= content_tag(role.builtin? ? 'em' : 'span', link_to(role.name, edit_role_path(role))) %></td>
  <td>
    <% unless role.builtin? || role.workflow_rules.exists? %>
      <span class="icon icon-warning">
        <%= sprite_icon('warning', l(:text_role_no_workflow)) %> (<%= link_to l(:button_edit), edit_workflows_path(:role_id => role) %>)
      </span>
    <% end %>
  </td>
  <td class="buttons">
    <%= reorder_handle(role) unless role.builtin? %>
    <%= link_to sprite_icon('copy', l(:button_copy)), new_role_path(:copy => role), :class => 'icon icon-copy' %>
    <%= delete_link role_path(role) unless role.builtin? %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>

<% html_title(l(:label_role_plural)) -%>

<%= javascript_tag do %>
  $(function() { $("table.roles tbody").positionedItems({items: ".givable"}); });
<% end %>

redmine-6.0.5/app/views/roles/new.html.erb
<%= title [l(:label_role_plural), roles_path], l(:label_role_new) %>

<%= labelled_form_for @role do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

redmine-6.0.5/app/views/roles/permissions.html.erb
<%= title [l(:label_role_plural), roles_path], l(:label_permissions_report) %>

<div class="hide-when-print">
  <fieldset id="filters" class="collapsible collapsed">
    <legend onclick="toggleFieldset(this);" class="icon icon-collapsed">
      <%= sprite_icon("angle-right", rtl: true) %>
      <%= l(:label_filter_plural) %>
    </legend>
    <div style="display: none;">
      <%= form_tag({}, :method => :get) do %>
        <fieldset>
          <legend><%= toggle_checkboxes_link('#filters input[type=checkbox]:enabled') %></legend>
          <% Role.sorted.to_a.each do |role| %>
            <label>
              <%= check_box_tag "ids[]", role.id, @roles.include?(role) %>
              <%= role.name %>
            </label>
          <% end %>
        </fieldset>
        <p>
          <%= submit_tag l(:button_apply), :name => nil %>
          <%= link_to l(:button_clear), permissions_roles_path, :class => 'icon icon-reload' %>
        </p>
      <% end %>
    </div>
  </fieldset>
</div>

<%= form_tag(permissions_roles_path, :id => 'permissions_form') do %>
<% @roles.each do |role| %>
    <%= hidden_field_tag "permissions[#{role.id}][]", '', :id => nil %>
<% end %>
<div class="autoscroll">
<table class="list permissions">
<thead>
    <tr>
    <th><%=l(:label_permissions)%></th>
    <% @roles.each do |role| %>
    <th>
        <%= toggle_checkboxes_link("input.role-#{role.id}") %>
        <%= content_tag(role.builtin? ? 'em' : 'span', role.name) %>
    </th>
    <% end %>
    </tr>
</thead>
<tbody>
<% perms_by_module = @permissions.group_by {|p| p.project_module.to_s} %>
<% perms_by_module.keys.sort.each do |mod| %>
    <% unless mod.blank? %>
        <tr class="group open">
          <td>
            <span class="expander icon icon-expanded" onclick="toggleRowGroup(this);"><%= sprite_icon("angle-down") %></span>
            <%= l_or_humanize(mod, :prefix => 'project_module_') %>
          </td>
          <% @roles.each do |role| %>
          <td class="role"><%= role.name %></td>
          <% end %>
        </tr>
    <% end %>
    <% perms_by_module[mod].each do |permission| %>
        <% humanized_perm_name = l_or_humanize(permission.name, :prefix => 'permission_') %>
        <tr class="permission-<%= permission.name %>">
        <td class="name">
            <%= toggle_checkboxes_link(".permission-#{permission.name} input") %>
            <%= humanized_perm_name %>
        </td>
        <% @roles.each do |role| %>
          <% if role.setable_permissions.include? permission %>
            <td title="<%= "#{humanized_perm_name} (#{role.name})" %>">
              <%= check_box_tag "permissions[#{role.id}][]", permission.name, (role.permissions.include? permission.name), :id => nil, :class => "role-#{role.id}" %>
            </td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
        </tr>
    <% end %>
<% end %>
</tbody>
</table>
</div>
<p><%= check_all_links 'permissions_form' %></p>
<p><%= submit_tag l(:button_save) %></p>
<% end %>
<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters 'CSV', {}, :onclick => "showModal('csv-export-options', '330px'); return false;" %>
<% end %>
<div id="csv-export-options" style="display: none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= form_tag(permissions_roles_path(:format => 'csv'), :method => :get, :id => 'csv-export-form') do %>
  <%= export_csv_encoding_select_tag %>
  <%= export_csv_separator_select_tag %>
  <p class="buttons">
    <%= submit_tag l(:button_export), :name => nil, :onclick => 'hideModal(this);', :data => {:disable_with => false} %>
    <%= link_to_function l(:button_cancel), 'hideModal(this);' %>
  </p>
  <% end %>
</div>